name: terraform-check
description: Check if there are terraform changes to apply
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend configs to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file"
    required: false
  variables:
    description: Variable definitions
    required: false
  var:
    description: Comma separated list of vars to set, e.g. 'foo=bar'
    required: false
    deprecationMessage: Use the variables input instead.
  var_file:
    description: List of var file paths, one per line
    required: false
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: "0"

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:4fec008558a518785e1ac10e1f601a584d2642a013e871f2c50134f7ed14f361
  entrypoint: /entrypoints/check.sh

branding:
  icon: globe
  color: purple
